site_name: Zibersegurtasuna Web Garapenean - 2025-2026
theme:
  name: material
  language: eu
  logo: images/logo.png
  favicon: http://fptxurdinaga.eus/wp-content/uploads/2022/10/favicon-96x96-1.png
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - navigation.instant
    - navigation.expand # Esto permite expandir/colapsar, pero necesitamos ajustar el CSS
  palette:
    - scheme: default
      primary: '#004c95'
      accent: '#e95f15'
    - scheme: slate
      primary: '#004c95'
      accent: '#e95f15'
      toggle:
        icon: material/weather-night
        name: Modu iluna
extra_css:
- stylesheets/extra.css
extra_javascript:
- scripts/checkboxes.js
- javascripts/sidebar.js
plugins:
- search
markdown_extensions:
- admonition
- pymdownx.tasklist:          # ← nuevo
    clickable_checkbox: true  #  hace los checkboxes interactivos
    custom_checkbox: true     #  usa los iconos de Material
- toc:
    permalink: true
- footnotes
- tables
nav:
  - Hasiera: index.md
  - '1. Oinarriak eta mehatxu arruntak':
    - '1.1. Web Garapenean Zibersegurtasunaren Sarrera': oinarriak_mehatxuak/sarrera.md
    - '1.2. Webaren funtzionamenduaren oinarriak': oinarriak_mehatxuak/web_oinarriak.md
    - '1.3. Web Hacking-erako sarrera': oinarriak_mehatxuak/web_hacking_sarrera.md    
  - '2. OWASP Top 10':
    - 'Aurkezpena (OWASP Top 10)': oinarriak_mehatxuak/owasp_top10.md
    - '2.1. Broken Access Control': ariketak/broken_access_control.md
    - '2.2. Cryptographic Failures': ariketak/cryptographic_failures.md
    - '2.3. Injection': ariketak/injection.md
    - '2.4. Insecure Design': ariketak/insecure_design.md
    - '2.5. Security Misconfiguration': ariketak/security_misconfiguration.md
    - '2.6. Vulnerable and Outdated Components': ariketak/vulnerable_obsolete_components.md
    - '2.7. Identification and Authentication Failures': ariketak/identification_authentication_failures.md
    - '2.8. Software and Data Integrity Failures': ariketak/software_data_integrity_failures.md
    - '2.9. Security Logging and Monitoring Failures': ariketak/security_logging_monitoring_failures.md
    - '2.10. Server-Side Request Forgery': ariketak/server_side_request_forgery.md
  - '3. Eraso eta defentsa oinarrizkoak':
    - '3.1. Injekzioen aurkako defentsak': eraso_defentsak/injekzioak.md
    - '3.2. Autentifikazio eta saioen segurtasuna': eraso_defentsak/autentifikazioa.md
    - '3.3. Sarbide-kontrola eta konfigurazio segurua': eraso_defentsak/sarbide_kontrola.md
  # - '4. Datuen babesa eta tresna praktikoak':
  #   - '4.1. Datu sentikorren babesa': datu_babesa/datu_sentikorrak.md
  #   - '4.2. APIen eta dependentzien segurtasuna': datu_babesa/api_segurtasuna.md
  #   - '4.3. Tresna praktikoen sarrera': datu_babesa/tresnak.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
